---
name: HTNProtocol
version: 0.0.1
main: HTNProtocol\Main
api: 4.5.2
src-namespace-prefix: HTNProtocol
commands:
    test:
        description: Test Command
        usage: "/test"
        permission: HTNProtocol.command.test
    connect_discord:
        description: Generates a code for you to connect to discord
        usage: "/connectdc"
        permission: HTNProtocol.command.connect_discord
permissions:
    HTNProtocol.command.test:
        default: op
        description: "test"
    HTNProtocol.command.connect_discord:
        default: op
        description: "test"
